### ISSUE TITLE
Please add an git ignore to your repository ^_^

### ISSUE THREAD

**Issue by sycLin** [benchou1919/DeYiDL#1]
### Why
---
There are things we don't like to "version-control" them.
Ex.
- [x] ".DS_Store" files. (system description files)
- [x] ".swap" files. (temporary files)
- [x] ".class" files. (compiled sources)

### How
---
You can find a lot of sample `.gitignore` online :)

**Comment by m516825** [comment]
??

**Comment by BoyoChen** [comment]
？？？？

**Comment by gdoggg2032** [comment]
Steven :)

you Boyo 2.0!!

**Comment by benchou1919** [comment]
DONE
